-- Generated by scripts/hypr2lua.
-- Source: omarchy-monolith-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(c4a7e7ff)", "rgba(3e8fb0ff)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(6e6a86ff)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 0,
    gaps_out = 0,
    border_size = 3,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    rounding_power = 0,
    blur = {
      enabled = true,
      size = 5,
      passes = 3,
      noise = 0.1,
    },
    shadow = {
      enabled = false,
    },
  },
})

hl.curve("bezier01", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 7,
  bezier = "bezier01",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 7,
  bezier = "bezier01",
  style = "slide",
})

hl.window_rule({
  name = "windowrule-1",
  opacity = "1.0 override",
  match = {
    class = "^(brave-youtube\\\\.com__-Default)$",
  },
})
hl.window_rule({
  name = "windowrule-2",
  opacity = "1.0 override",
  match = {
    class = "^(chrome-youtube\\\\.com__-Default)$",
  },
})
