-- Generated by scripts/hypr2lua.
-- Source: omarchy-monolith-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(c4a7e7ff)", "rgba(9ccfd8ff)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(56526eff)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 0,
    gaps_out = 0,
    border_size = 3,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    rounding_power = 0,
    blur = {
      enabled = true,
      size = 8,
      passes = 3,
      noise = 0.035,
      contrast = 1.05,
      brightness = 0.75,
      vibrancy = 0.1,
      vibrancy_darkness = 0.2,
      ignore_opacity = true,
      new_optimizations = true,
    },
    shadow = {
      enabled = false,
    },
  },
})

hl.curve("bezier01", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })
hl.curve("monolithQuick", { type = "bezier", points = { { 0.15, 0.85 }, { 0.25, 1 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "bezier01" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.5, bezier = "monolithQuick", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "monolithQuick", style = "popin 85%" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "bezier01" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.5, bezier = "monolithQuick" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 2, bezier = "monolithQuick" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.8, bezier = "monolithQuick" })
hl.animation({ leaf = "layers", enabled = true, speed = 2.5, bezier = "monolithQuick" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.5, bezier = "monolithQuick", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.8, bezier = "monolithQuick", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, bezier = "monolithQuick", style = "slide" })

hl.window_rule({
  name = "windowrule-1",
  opacity = "1.0 override",
  match = {
    class = "^(brave-youtube\\\\.com__-Default)$",
  },
})
hl.window_rule({
  name = "windowrule-2",
  opacity = "1.0 override",
  match = {
    class = "^(chrome-youtube\\\\.com__-Default)$",
  },
})
