$activeBorderColor = rgba(c4a7e7ff) rgba(3e8fb0ff) 45deg                  # pine
$inactiveBorderColor = rgba(6e6a86ff)                 # muted


windowrule {
  name = windowrule-1
  opacity = 1.0 override
  match:class = ^(brave-youtube\\.com__-Default)$
}

windowrule {
  name = windowrule-2
  opacity = 1.0 override
  match:class = ^(chrome-youtube\\.com__-Default)$
}

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 0
    gaps_out = 0
    border_size = 3
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    # Use round window corners
    rounding = 0
    rounding_power = 0
    # active_opacity = 0.85
    #inactive_opacity = 0.7
    blur {
        enabled = true
        size = 8
        passes = 3
        noise = 0.035
        contrast = 1.05
        brightness = 0.75
        vibrancy = 0.1
        vibrancy_darkness = 0.2
        ignore_opacity = true
        new_optimizations = true
    }
    shadow {
        enabled = false
    }
}

animations {
    bezier = bezier01, 0.65, 0, 0.35, 1
    bezier = monolithQuick, 0.15, 0.85, 0.25, 1

    animation = windows, 1, 3, bezier01
    animation = windowsIn, 1, 2.5, monolithQuick, popin 85%
    animation = windowsOut, 1, 2, monolithQuick, popin 85%
    animation = border, 1, 3, bezier01
    animation = fade, 1, 2.5, monolithQuick
    animation = fadeIn, 1, 2, monolithQuick
    animation = fadeOut, 1, 1.8, monolithQuick
    animation = layers, 1, 2.5, monolithQuick
    animation = layersIn, 1, 2.5, monolithQuick, fade
    animation = layersOut, 1, 1.8, monolithQuick, fade
    animation = workspaces, 1, 2.5, monolithQuick, slide
  }
